services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
            fastapi run app/main.py"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/city_temperature.db
    env_file:
      - .env
